Kubernetes logging
otus-kuber-2020-04/semer-ilya_platform pull request #11
Opened 2020-06-29 22:37 UTC by semer-ilya

# Выполнено ДЗ №

 - [ + ] Основное ДЗ
 - [ + ] Задание со *

## В процессе сделано:
 - установлен хипстершоп
 - установлен EFK
 - установлен Nginx-ingress
 - установлен Loki
 - установлен prometheus + Grafana + alrtmanager

## Как запустить проект:
 Выполнить ямлики из папки kubernetes-logging, загрузить Борды оттуда же

## Как проверить работоспособность:
 Зайти в морды киданы и графины и там проверить визуалку

## PR checklist:
 - [ + ] Выставлен label с темой домашнего задания

2020-06-30 09:28 UTC, Jasstkn requested changes
Добрый день. Не вижу у вас выполнения заданий по ElasticSearch мониторингу (слайд 2.2). Также дашборд для ингрессов не совсем корректно отображает данные.
И у вас в PR указано выполнение заданий со звездочками, но не вижу описания того, что было выполнено и как это проверить - поэтому возвращаю на доработку.
<img width="1375" alt="Screenshot 2020-06-30 at 12 27 38" src="https://user-images.githubusercontent.com/20466436/86109473-1913a000-bacd-11ea-85d9-545a04577cf5.png">

2020-06-30 19:01 UTC, semer-ilya commented
> Добрый день. Не вижу у вас выполнения заданий по ElasticSearch мониторингу (слайд 2.2). Также дашборд для ингрессов не совсем корректно отображает данные.
> И у вас в PR указано выполнение заданий со звездочками, но не вижу описания того, что было выполнено и как это проверить - поэтому возвращаю на доработку.
> <img alt="Screenshot 2020-06-30 at 12 27 38" width="1375" src="https://user-images.githubusercontent.com/20466436/86109473-1913a000-bacd-11ea-85d9-545a04577cf5.png">

Да, чот ластик я проморгал мальца как то((( Доделаю... Хотя там вроде только шаблон загрузить и поранять ноды... А по инресам может что то показаться не так ибо в задании сказано "развернуть ингрес"... Ну я по привычке и развернул его в отдельном неймспейсе... Звездочки частично сделаны, можно не считать) 
Попарвлю завтра)

2020-06-30 21:00 UTC, Jasstkn commented
> > Добрый день. Не вижу у вас выполнения заданий по ElasticSearch мониторингу (слайд 2.2). Также дашборд для ингрессов не совсем корректно отображает данные.
> > И у вас в PR указано выполнение заданий со звездочками, но не вижу описания того, что было выполнено и как это проверить - поэтому возвращаю на доработку.
> > <img alt="Screenshot 2020-06-30 at 12 27 38" width="1375" src="https://user-images.githubusercontent.com/20466436/86109473-1913a000-bacd-11ea-85d9-545a04577cf5.png">
> 
> Да, чот ластик я проморгал мальца как то((( Доделаю... Хотя там вроде только шаблон загрузить и поранять ноды... А по ингресам может что то показаться не так ибо в задании сказано "развернуть ингрес"... Ну я по привычке и развернул его в отдельном неймспейсе... Пришлось чуть повозиться... Звездочки частично сделаны, можно не считать)
> Попарвлю завтра)
На графике для ингресса в рейте откуда-то 5 тысяч процентов)

2020-07-01 13:17 UTC, semer-ilya commented
> > Добрый день. Не вижу у вас выполнения заданий по ElasticSearch мониторингу (слайд 2.2). Также дашборд для ингрессов не совсем корректно отображает данные.
> > И у вас в PR указано выполнение заданий со звездочками, но не вижу описания того, что было выполнено и как это проверить - поэтому возвращаю на доработку.
> > <img alt="Screenshot 2020-06-30 at 12 27 38" width="1375" src="https://user-images.githubusercontent.com/20466436/86109473-1913a000-bacd-11ea-85d9-545a04577cf5.png">
> 
> Да, чот ластик я проморгал мальца как то((( Доделаю... Хотя там вроде только шаблон загрузить и поранять ноды... А по ингресам может что то показаться не так ибо в задании сказано "развернуть ингрес"... Ну я по привычке и развернул его в отдельном неймспейсе... Пришлось чуть повозиться... Звездочки частично сделаны, можно не считать)
> Попарвлю завтра)
> На графике для ингресса в рейте откуда-то 5 тысяч процентов)

Хах) Ну, больше- не меньше))) 
Чуть позже сяду чекну чо там такое)

2020-07-06 19:25 UTC, semer-ilya commented
Дашборедец по ластику поправил http://grafana.35.205.47.218.xip.io/d/_x-6ALMMk/elasticsearch?orgId=1&from=now-30m&to=now&var-interval=1m&var-cluster=elasticsearch&var-node=All&refresh=5s (admin / superpassword)

2020-07-06 20:31 UTC, semer-ilya commented
Дашборд по жинксу переделал https://github.com/otus-kuber-2020-04/semer-ilya_platform/blob/kubernetes-logging/kubernetes-logging/nginx-ingress.json

2020-07-07 07:25 UTC, Jasstkn approved these changes
Доброе утро еще раз =)
Теперь все выглядит отлично! Принято 😉

2020-07-07 07:25 UTC, merged