kubernetes-gitops-1
otus-kuber-2020-04/semer-ilya_platform pull request #18
Opened 2020-10-05 23:29 UTC by semer-ilya

# Выполнено ДЗ №

 - [ + ] Основное ДЗ
 - [ - ] Задание со *

## В процессе сделано:
см ридми в папке с ДЗ

## Как запустить проект:
 см ридми в папке с ДЗ

## Как проверить работоспособность:
см ридми в папке с ДЗ

## PR checklist:
 - [ + ] Выставлен label с темой домашнего задания

2020-10-06 19:47 UTC, Jasstkn requested changes

2020-10-06 19:47 UTC, Jasstkn commented on kubernetes-gitops/README.md
> +ссылка на репу: https://gitlab.com/FUCKir89/microservices-demo
Накинь прав на просмотр - доступа нет :(

2020-10-06 19:48 UTC, Jasstkn commented on kubernetes-gitops/README.md
> +ссылка на репу: https://gitlab.com/FUCKir89/microservices-demo
https://gitlab.com/Jasstkn

2020-10-06 21:20 UTC, semer-ilya commented on kubernetes-gitops/README.md
> +ссылка на репу: https://gitlab.com/FUCKir89/microservices-demo
Дал мейнтейнера, чтоб все можно было) Там, если что, кати последний тэк инфры чтоб кластер поднять и поднимай приложуху, если надо, бабло на GCP еще осталось)

2020-10-06 21:20 UTC, semer-ilya commented on kubernetes-gitops/README.md
> +ссылка на репу: https://gitlab.com/FUCKir89/microservices-demo
Ключ флюкса в репу если что прописывай, не стесняйся)

2020-10-07 15:04 UTC, Jasstkn approved these changes
Домашку принимаю, так как вижу, что по ходу выполнения все верно - подробный фидбек чуть позже дам 👍

2020-10-07 15:04 UTC, merged