Kubernetes networks
otus-kuber-2020-04/semer-ilya_platform pull request #6
Opened 2020-05-23 21:09 UTC by semer-ilya

# Выполнено ДЗ №

 - [ + ] Основное ДЗ
 - [ + ] Задание со *

## В процессе сделано:
 - Разобрались с Metallb
 - Разобрались с ClusterIP
 - Разобрались с IPVS
 - Разобрались с Ingress

## Как запустить проект:
 - Для деплоя канарейки выполнить все ямлики из папки kubernetes-networks/canary/

## Как проверить работоспособность:
 - перейти по ссылке http://172.17.255.2/web/index.html

## PR checklist:
 - [ + ] Выставлен label с темой домашнего задания

2020-05-23 21:30 UTC, semer-ilya commented
Не понимаю что ему не нравится( В одном из тестов говорит, что http://172.17.255.2:80/web/index.html не открывается, хотя локально все окнорм(((
Так же прошу глянуть канарейку) Направил трафик "фифти-фифти", но не уверен, что все правильно сделал... Там в файлике kubernetes-networks/canary/canary-ingress.yaml два ингресса, один с канарейкой в аннотации и смотрит на один сервис, второй без канарейки и смотрит на второй сервис... Я правильно понял, что оба ингреса висят на одном адресе, трафик смотрит на них аннотации и дальше в зависимости от того есть ли там канарейка и что в ней прописано раскидывает ся на один или другой сервис?

2020-05-24 18:12 UTC, Jasstkn requested changes
Добрый вечер! Домашнее задание выполнено верно - видимо тесты пролагали :(
В домашнем задании с canary предполагалось использование одного из предоставленных вариантов. Вы правильно поняли про то, что оба ингресса висят на одном IP адресе и по хедеру или весу уже запросы роутятся на конечные сервисы :) Задание с kubernetes-dashboard сделано верно - вы молодец!

По приоритезации запросов есть подробности в документации: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

Также напоминаю, что условием принятия домашнего задания является наличие ридми с ходом выполнения работы и командами для проверки работоспособности (!!!) - не забывайте в следующий раз =)

2020-05-24 18:12 UTC, Jasstkn commented on kubernetes-networks/canary/canary-ingress.yaml
> +    nginx.ingress.kubernetes.io/canary-weight: "50"
Вам необходимо выбрать один из способов осуществлять canary или по весу, или по header.
Про приоритезацию написано в документации: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

2020-05-24 18:40 UTC, Jasstkn approved these changes

2020-05-24 18:40 UTC, merged

2020-05-25 06:56 UTC, FUCKir89 commented
> Не понимаю что ему не нравится( В одном из тестов говорит, что http://172.17.255.2:80/web/index.html не открывается, хотя локально все окнорм(((
> Так же прошу глянуть канарейку) Направил трафик "фифти-фифти", но не уверен, что все правильно сделал... Там в файлике kubernetes-networks/canary/canary-ingress.yaml два ингресса, один с канарейкой в аннотации и смотрит на один сервис, второй без канарейки и смотрит на второй сервис... Я правильно понял, что оба ингреса висят на одном адресе, трафик смотрит на них аннотации и дальше в зависимости от того есть ли там канарейка и что в ней прописано раскидывает ся на один или другой сервис?

Добрый день!) Спасибо большое за Ваш комментарий!)
1. Так я не понял, у меня в итоге с канарейкой верно сделано или нет?)
2. А в пулреквесте ридми не достаточно? Надо в самой репе его сделать?) (просто, как подсказал опыт курса не девопсе, смысловой нагрузки от этого ридми немного, а под конец курса получаестся кособокая портянка)

2020-05-25 06:58 UTC, semer-ilya commented
> Добрый вечер! Домашнее задание выполнено верно - видимо тесты пролагали :(
> В домашнем задании с canary предполагалось использование одного из предоставленных вариантов. Вы правильно поняли про то, что оба ингресса висят на одном IP адресе и по хедеру или весу уже запросы роутятся на конечные сервисы :) Задание с kubernetes-dashboard сделано верно - вы молодец!
> 
> По приоритезации запросов есть подробности в документации: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary
> 
> Также напоминаю, что условием принятия домашнего задания является наличие ридми с ходом выполнения работы и командами для проверки работоспособности (!!!) - не забывайте в следующий раз =)

Добрый день!) Спасибо большое за Ваш комментарий!)

Так я не понял, у меня в итоге с канарейкой верно сделано или нет?)
А в пулреквесте ридми не достаточно? Надо в самой репе его сделать?) (просто, как подсказал опыт курса не девопсе, смысловой нагрузки от этого ридми немного, а под конец курса получаестся кособокая портянка)

2020-05-25 06:59 UTC, Jasstkn commented
> > Не понимаю что ему не нравится( В одном из тестов говорит, что http://172.17.255.2:80/web/index.html не открывается, хотя локально все окнорм(((
> > Так же прошу глянуть канарейку) Направил трафик "фифти-фифти", но не уверен, что все правильно сделал... Там в файлике kubernetes-networks/canary/canary-ingress.yaml два ингресса, один с канарейкой в аннотации и смотрит на один сервис, второй без канарейки и смотрит на второй сервис... Я правильно понял, что оба ингреса висят на одном адресе, трафик смотрит на них аннотации и дальше в зависимости от того есть ли там канарейка и что в ней прописано раскидывает ся на один или другой сервис?
> 
> Добрый день!) Спасибо большое за Ваш комментарий!)
> 
> 1. Так я не понял, у меня в итоге с канарейкой верно сделано или нет?)
> 2. А в пулреквесте ридми не достаточно? Надо в самой репе его сделать?) (просто, как подсказал опыт курса не девопсе, смысловой нагрузки от этого ридми немного, а под конец курса получаестся кособокая портянка)

Да, канарейка сделана правильно. Я вам просто немного дополнила то, что вы написали. 
У вас нет команд для проверки работоспособности заданий со звездочкой - а это затрудняет проверку преподавателям, так как большинство решений так или иначе различается и каждый раз приходится писать новые команды для проверки)

2020-05-25 07:05 UTC, semer-ilya commented
> > > Не понимаю что ему не нравится( В одном из тестов говорит, что http://172.17.255.2:80/web/index.html не открывается, хотя локально все окнорм(((
> > > Так же прошу глянуть канарейку) Направил трафик "фифти-фифти", но не уверен, что все правильно сделал... Там в файлике kubernetes-networks/canary/canary-ingress.yaml два ингресса, один с канарейкой в аннотации и смотрит на один сервис, второй без канарейки и смотрит на второй сервис... Я правильно понял, что оба ингреса висят на одном адресе, трафик смотрит на них аннотации и дальше в зависимости от того есть ли там канарейка и что в ней прописано раскидывает ся на один или другой сервис?
> > 
> > 
> > Добрый день!) Спасибо большое за Ваш комментарий!)
> > 
> > 1. Так я не понял, у меня в итоге с канарейкой верно сделано или нет?)
> > 2. А в пулреквесте ридми не достаточно? Надо в самой репе его сделать?) (просто, как подсказал опыт курса не девопсе, смысловой нагрузки от этого ридми немного, а под конец курса получаестся кособокая портянка)
> 
> Да, канарейка сделана правильно. Я вам просто немного дополнила то, что вы написали.
> У вас нет команд для проверки работоспособности заданий со звездочкой - а это затрудняет проверку преподавателям, так как большинство решений так или иначе различается и каждый раз приходится писать новые команды для проверки) Если вы в описании PR будете подробнее описывать проделанную работу и указывать команды для проверки - отдельный ридми не нужен. Также, часто коллеги кладут отдельный ридми в каждую папку с дз - так избегается каша, а на главной ридми-оглавление с ссылками на другие.

Ага, понял! Учту и приму к сведению) Спасибо большое!)